### PR TITLE
update downstream to reflect preferred API for adding topics.

### LINKED ISSUE #13: Replace `publishing` with `withTopics`
Lagom `1.3.6` ~deprecates~ _may deprecate_ `publishing` in favor of `withTopics` on the javadsl `Descriptor`.

When `1.3.6` is out, this `g8` template ~needs~ _may need_ updating.

(edit: updated tense)

### PR DESCRIPTION
**Pull request by erip**
Fixes #13.

### CODE REVIEW

**Comment by ignasi35** [comment]
Can't be merged until `1.3.6` is available and is the default version for this template.

**Comment by erip** [comment]
@ignasi35 Sure thing. It's here when everything is ready for it.

**Comment by TimMoore** [comment]
@erip this is ready now. If you can rebase your branch onto the latest `master` (or merge `master` into it) it should pass now.

**Comment by ignasi35** [comment]
Closed. Continued work in #18

**Pull request closed without merging**
